# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encoder.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encoder.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rencoder.proto\"0\n\x14TopKDocumentsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\"?\n\x16RerankDocumentsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\r\n\x05query\x18\x02 \x01(\t\x12\t\n\x01k\x18\x03 \x01(\x05\"-\n\rDocumentMatch\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\"\x99\x01\n\x0eSearchResponse\x12\x1f\n\x07matches\x18\x01 \x03(\x0b\x32\x0e.DocumentMatch\x12$\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x15.SearchResponse.Error\"@\n\x05\x45rror\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x16\n\x12INDEX_IS_NOT_READY\x10\x01\x12\x11\n\rUNKNOWN_ERROR\x10\x02\"L\n\x0bSyncRequest\x12\x14\n\ndocumentId\x18\x01 \x01(\x05H\x00\x12\r\n\x03\x61ll\x18\x02 \x01(\x08H\x00\x12\x0e\n\x06\x64\x65lete\x18\x03 \x01(\x08\x42\x08\n\x06target\"\x92\x01\n\x0cSyncResponse\x12\"\n\x05\x65rror\x18\x01 \x01(\x0e\x32\x13.SyncResponse.Error\"^\n\x05\x45rror\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x1c\n\x18\x41NOTHER_SYNC_IN_PROGRESS\x10\x01\x12\x16\n\x12INDEX_IS_NOT_READY\x10\x02\x12\x11\n\rUNKNOWN_ERROR\x10\x03\x32\xb0\x01\n\x07\x45ncoder\x12;\n\x11\x46indTopKDocuments\x12\x15.TopKDocumentsRequest\x1a\x0f.SearchResponse\x12\x43\n\x17RetrieveRerankDocuments\x12\x17.RerankDocumentsRequest\x1a\x0f.SearchResponse\x12#\n\x04Sync\x12\x0c.SyncRequest\x1a\r.SyncResponseb\x06proto3'
)



_SEARCHRESPONSE_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='SearchResponse.Error',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEX_IS_NOT_READY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=269,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_SEARCHRESPONSE_ERROR)

_SYNCRESPONSE_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='SyncResponse.Error',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANOTHER_SYNC_IN_PROGRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INDEX_IS_NOT_READY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=466,
  serialized_end=560,
)
_sym_db.RegisterEnumDescriptor(_SYNCRESPONSE_ERROR)


_TOPKDOCUMENTSREQUEST = _descriptor.Descriptor(
  name='TopKDocumentsRequest',
  full_name='TopKDocumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='TopKDocumentsRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='TopKDocumentsRequest.k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=65,
)


_RERANKDOCUMENTSREQUEST = _descriptor.Descriptor(
  name='RerankDocumentsRequest',
  full_name='RerankDocumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='RerankDocumentsRequest.ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query', full_name='RerankDocumentsRequest.query', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='RerankDocumentsRequest.k', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=130,
)


_DOCUMENTMATCH = _descriptor.Descriptor(
  name='DocumentMatch',
  full_name='DocumentMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DocumentMatch.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='DocumentMatch.distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=177,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matches', full_name='SearchResponse.matches', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='SearchResponse.error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEARCHRESPONSE_ERROR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=333,
)


_SYNCREQUEST = _descriptor.Descriptor(
  name='SyncRequest',
  full_name='SyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='documentId', full_name='SyncRequest.documentId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all', full_name='SyncRequest.all', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete', full_name='SyncRequest.delete', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='target', full_name='SyncRequest.target',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=335,
  serialized_end=411,
)


_SYNCRESPONSE = _descriptor.Descriptor(
  name='SyncResponse',
  full_name='SyncResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='SyncResponse.error', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYNCRESPONSE_ERROR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=560,
)

_SEARCHRESPONSE.fields_by_name['matches'].message_type = _DOCUMENTMATCH
_SEARCHRESPONSE.fields_by_name['error'].enum_type = _SEARCHRESPONSE_ERROR
_SEARCHRESPONSE_ERROR.containing_type = _SEARCHRESPONSE
_SYNCREQUEST.oneofs_by_name['target'].fields.append(
  _SYNCREQUEST.fields_by_name['documentId'])
_SYNCREQUEST.fields_by_name['documentId'].containing_oneof = _SYNCREQUEST.oneofs_by_name['target']
_SYNCREQUEST.oneofs_by_name['target'].fields.append(
  _SYNCREQUEST.fields_by_name['all'])
_SYNCREQUEST.fields_by_name['all'].containing_oneof = _SYNCREQUEST.oneofs_by_name['target']
_SYNCRESPONSE.fields_by_name['error'].enum_type = _SYNCRESPONSE_ERROR
_SYNCRESPONSE_ERROR.containing_type = _SYNCRESPONSE
DESCRIPTOR.message_types_by_name['TopKDocumentsRequest'] = _TOPKDOCUMENTSREQUEST
DESCRIPTOR.message_types_by_name['RerankDocumentsRequest'] = _RERANKDOCUMENTSREQUEST
DESCRIPTOR.message_types_by_name['DocumentMatch'] = _DOCUMENTMATCH
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
DESCRIPTOR.message_types_by_name['SyncRequest'] = _SYNCREQUEST
DESCRIPTOR.message_types_by_name['SyncResponse'] = _SYNCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopKDocumentsRequest = _reflection.GeneratedProtocolMessageType('TopKDocumentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOPKDOCUMENTSREQUEST,
  '__module__' : 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:TopKDocumentsRequest)
  })
_sym_db.RegisterMessage(TopKDocumentsRequest)

RerankDocumentsRequest = _reflection.GeneratedProtocolMessageType('RerankDocumentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _RERANKDOCUMENTSREQUEST,
  '__module__' : 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:RerankDocumentsRequest)
  })
_sym_db.RegisterMessage(RerankDocumentsRequest)

DocumentMatch = _reflection.GeneratedProtocolMessageType('DocumentMatch', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTMATCH,
  '__module__' : 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:DocumentMatch)
  })
_sym_db.RegisterMessage(DocumentMatch)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCREQUEST,
  '__module__' : 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:SyncRequest)
  })
_sym_db.RegisterMessage(SyncRequest)

SyncResponse = _reflection.GeneratedProtocolMessageType('SyncResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNCRESPONSE,
  '__module__' : 'encoder_pb2'
  # @@protoc_insertion_point(class_scope:SyncResponse)
  })
_sym_db.RegisterMessage(SyncResponse)



_ENCODER = _descriptor.ServiceDescriptor(
  name='Encoder',
  full_name='Encoder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=563,
  serialized_end=739,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindTopKDocuments',
    full_name='Encoder.FindTopKDocuments',
    index=0,
    containing_service=None,
    input_type=_TOPKDOCUMENTSREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RetrieveRerankDocuments',
    full_name='Encoder.RetrieveRerankDocuments',
    index=1,
    containing_service=None,
    input_type=_RERANKDOCUMENTSREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Sync',
    full_name='Encoder.Sync',
    index=2,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENCODER)

DESCRIPTOR.services_by_name['Encoder'] = _ENCODER

# @@protoc_insertion_point(module_scope)
