# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import encoder_pb2 as encoder__pb2


class EncoderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindTopKDocuments = channel.unary_unary(
                '/Encoder/FindTopKDocuments',
                request_serializer=encoder__pb2.TopKDocumentsRequest.SerializeToString,
                response_deserializer=encoder__pb2.SearchResponse.FromString,
                )
        self.RetrieveRerankDocuments = channel.unary_unary(
                '/Encoder/RetrieveRerankDocuments',
                request_serializer=encoder__pb2.RerankDocumentsRequest.SerializeToString,
                response_deserializer=encoder__pb2.SearchResponse.FromString,
                )
        self.Sync = channel.unary_unary(
                '/Encoder/Sync',
                request_serializer=encoder__pb2.SyncRequest.SerializeToString,
                response_deserializer=encoder__pb2.SyncResponse.FromString,
                )


class EncoderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindTopKDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveRerankDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindTopKDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTopKDocuments,
                    request_deserializer=encoder__pb2.TopKDocumentsRequest.FromString,
                    response_serializer=encoder__pb2.SearchResponse.SerializeToString,
            ),
            'RetrieveRerankDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveRerankDocuments,
                    request_deserializer=encoder__pb2.RerankDocumentsRequest.FromString,
                    response_serializer=encoder__pb2.SearchResponse.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=encoder__pb2.SyncRequest.FromString,
                    response_serializer=encoder__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Encoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Encoder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindTopKDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Encoder/FindTopKDocuments',
            encoder__pb2.TopKDocumentsRequest.SerializeToString,
            encoder__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveRerankDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Encoder/RetrieveRerankDocuments',
            encoder__pb2.RerankDocumentsRequest.SerializeToString,
            encoder__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Encoder/Sync',
            encoder__pb2.SyncRequest.SerializeToString,
            encoder__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
